require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'docs/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'spec/dummy/db/migrate/*_enable_hstore.rb'
    - 'spec/dummy/db/migrate/*_logidze_install.rb'
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/FileName:
  Exclude:
    - 'lib/test-prof.rb'
    - '**/*.md'
