# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 6.0"
gem "pg", "~> 1.0"

gem "paper_trail", "~> 10.0"
gem "logidze", path: "../../.."
gem "fx"

gem "faker"

gem "memory_profiler"
gem "benchmark-ips"
